#!/bin/sh
case "$1" in
  start)
    echo "Starting aesdchar module"
    aesdchar_load
    ;;
  stop)
    echo "Stopping aesdchar module"
    aesdchar_unload
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
